Makefile

This installs just the script and python libraries, but does not
overwrite existing configs.  Useful for testing.

Add install-noconfig make target

---

osg_configure/configure_modules/bosco.py

os.path.samefile raises an OSError if either of the files doesn't exist.
Don't raise an error if the dest file doesn't exist. Do raise an error
if the source file doesn't exist. (SOFTWARE-2188)

Catch os.path.samefile error if ssh_key_loc doesn't exist

---

osg_configure/configure_modules/gratia.py

The new HTCondor-CE Probe is here: [SOFTWARE-2257](https://jira.opensciencegrid.org/browse/SOFTWARE-2257)
The new probe requires a very small amount of configuration, but it does need to set `SuppressGridLocalRecords = "1"` in order for the probe to not double count both pre-routed and post-routed jobs.

Add configuration for the new gratia HTCondor-CE Probe

---

config/30-gip.ini

Add the required attribute `cpu_platform` to the subcluster example from UNL.

Add required cpu_platform to example

---

osg_configure/configure_modules/gip.py
tests/test_gip.py

The GIP unit tests do not properly test some functionality if one of the `osg-ce` RPMs isn't installed, leading to bogus errors in the test suite. Fix that.

Improve GIP tests

---

osg_configure/configure_modules/siteattributes.py

Python does not have a built in way of checking for the MX record of a domain, and checking for the CNAME instead (which is what socket.gethostbyname() does) sometimes results in a bogus warning. Since we can't do the check right, it's better to remove it altogether; verifying the email format should be enough.

Remove domain check for email address (SOFTWARE-2271)

---

.travis.yml

By default, email notifications are sent to the committer and the commit author, if they are members of the repository (that is, they have push or admin permissions for public repositories, or if they have pull, push or admin permissions for private repositories).
Emails are sent when, on the given branch:
- a build was just broken or still is broken
- a previously broken build was just fixed

Allow emails to committers that cause failed builds.

---

osg_configure/configure_modules/gratia.py
tests/test_gratia.py

The absence of sites that are not controlled by the admin should not cause osg-configure to error out. (SOFTWARE-2123)

Relax checks on non-site-controlled hosts

---

osg_configure/configure_modules/misc.py
tests/configs/misc/lcmaps.db.fresh
tests/configs/misc/lcmaps.db.gridmap1
tests/configs/misc/lcmaps.db.gridmap2
tests/configs/misc/lcmaps.db.gums
tests/test_misc.py

Per SOFTWARE-1723, osg-configure should set the options in the authorized_only section of /etc/lcmaps.db based on whether the admin wants to use grid-mapfile auth or GUMS auth. This used to be a manual procedure.
Unit tests have been added for this functionality.

Edit authorized_only section of lcmaps.db

---

osg_configure/modules/utilities.py

If the buffer being passed to utilities.add_or_replace_setting() had no
newline at the end, the function would blindly append to the end of the
last line. Check and add a newline if necessary. (SOFTWARE-2244)

Fix add_or_replace_setting if buf has no newline at the end

---

osg_configure/configure_modules/misc.py
tests/configs/misc/lcmaps.db.missing_gridmap.post
tests/configs/misc/lcmaps.db.missing_gums.post

lcmaps.db files come with a comment block before the glexec section that
describes the glexec section. When the new content was placed at the end
of the authorize_only section, it would end up after this comment block,
making it look wrong and confusing. (SOFTWARE-2321)

Put new content into the beginning of the authorize_only section

---

tests/configs/misc/valid_settings.ini
tests/configs/misc/valid_settings2.ini

For SOFTWARE-2406. Some of the unit tests use a config with a value for `gums_host` that is not guaranteed to resolve. Since SOFTWARE-2319, osg-configure has started checking that the value for `gums_host` resolves if using "xacml" as the authentication method. This can lead to test failures. Fix that by using "localhost" as the `gums_host` for that test.
In addition, `gums_host` is meant to be ignored if not using "xacml". Make this explicit by putting a bogus `gums_host` in the test that does uses "local-gridmap" as the auth method.

Fix gums_host in unit tests

---

osg_configure/configure_modules/infoservices.py
osg_configure/modules/subcluster.py

This fixes an error when a 30-gip.ini file has a Resource Entry section but not a Subcluster section. (SOFTWARE-2478). Also add a test for this fix.

Detect "Resource Entry" section in subcluster.check_config()

---

osg_configure/configure_modules/gratia.py

This is for SOFTWARE-2311. For Gratia probe configs (ProbeConfig and urCollector.conf files): if the admin added any quotes to the settings in their osg configs, escape the quotes either in XML format (&quot;) for the ProbeConfig files, or in C format (\") for the urCollector.conf files.

Fix quoting in Gratia probe configs

---

osg_configure/modules/subcluster.py
tests/configs/gip/resourceentry.ini
tests/test_gip.py

SOFTWARE-2554. Unlike Subcluster sections, Resource Entry sections are not used for GIP/BDII, only for the CE collector and AGiS. Allow omitting attributes from Resource Entry sections that aren't needed for the latter two systems.

Don't require some attributes for Resource Entry sections

---

Makefile

the shell interprets backticks inside doublequotes

avoid shell syntax error

---

osg_configure/configure_modules/storage.py

Turn a missing `app_dir` into a warning, not an error

---

osg_configure/configure_modules/infoservices.py

This fixes logging in ensure_valid_user_vo_file and makes it so that the gums server doesn't get queried if there's already a working user-vo-map, which should get rid of the performance issues.
Known issues:
* the 'this may take a while' warning only shows up in the logfile, which is pretty useless. I think it will be fixed when I get around to fixing the logging (SOFTWARE-2744)
* the user-vo-map file gets populated once, and then never updated; normally, gums-host-cron runs from cron and updates it. I will make a new ticket for that

Fixes for SOFTWARE-2482

---

osg_configure/configure_modules/infoservices.py

This fixes logging in ensure_valid_user_vo_file and makes it so that the gums server doesn't get queried if there's already a working user-vo-map, which should get rid of the performance issues.
Known issues:
* the 'this may take a while' warning only shows up in the logfile, which is pretty useless. I think it will be fixed when I get around to fixing the logging (SOFTWARE-2744)
* the user-vo-map file gets populated once, and then never updated; normally, gums-host-cron runs from cron and updates it. I will make a new ticket for that

Fixes for SOFTWARE-2482 (v1)

---

osg_configure/configure_modules/misc.py

This allows `osg-configure -v` to error out if glexec is on.

Check for glexec use in check_attributes()  (SOFTWARE-2772)

---

osg_configure/modules/utilities.py

This solves trying to run `/usr/sbin` when no fetch-crl package is found.
No need to detect whether fetch-crl or fetch-crl3 is installed --
fetch-crl3 does not exist on RHEL > 5.
Missing /usr/sbin/fetch-crl is already handled.

Always use /usr/sbin/fetch-crl (SOFTWARE-2891)

---

osg_configure/configure_modules/localsettings.py
tests/configs/localsettings/bogusquote.ini
tests/configs/localsettings/bogusvarname.ini
tests/configs/localsettings/local_settings1.ini
tests/test_local_settings.py

Make sure the attributes in the Local Settings section are valid identifiers -- meaning they can be used as bash variables. Also check that the user didn't quote the value (since they already get quoted in the files osg-configure generates).

Validate Local Settings vars (SOFTWARE-3131)

---

osg_configure/configure_modules/bosco.py
osg_configure/configure_modules/gratia.py
osg_configure/configure_modules/rsv.py
osg_configure/configure_modules/storage.py
osg_configure/modules/baseconfiguration.py
osg_configure/modules/configfile.py
osg_configure/modules/gums_supported_vos.py
osg_configure/modules/utilities.py
osg_configure/modules/validation.py
scripts/osg-configure
tests/test_condor.py
tests/test_gateway.py
tests/test_gratia.py
tests/test_info_services.py
tests/test_local_settings.py
tests/test_lsf.py
tests/test_misc.py
tests/test_pbs.py
tests/test_resourcecatalog.py
tests/test_sge.py
tests/test_siteattributes.py
tests/test_slurm.py
tests/test_squid.py
tests/test_storage.py
tests/test_subcluster.py
tests/test_utilities.py

These are some safe changes to start making osg-configure Python 3-compatible.
Commands run:
python-modernize -w -f lib2to3.fixes.fix_except scripts/osg-configure osg_configure/*/*.py tests/*.py
python-modernize -w -f lib2to3.fixes.fix_numliterals scripts/osg-configure osg_configure/*/*.py tests/*.py
python-modernize -w -f libmodernize.fixes.fix_print scripts/osg-configure osg_configure/*/*.py tests/*.py

Modernize Python syntax

---

config/01-squid.ini
osg_configure/configure_modules/squid.py
tests/configs/squid/ignored.ini
tests/configs/squid/squid1.ini
tests/configs/squid/squid_bad_cache.ini
tests/configs/squid/squid_bad_host.ini
tests/configs/squid/squid_bad_host2.ini
tests/configs/squid/squid_bad_mem.ini
tests/configs/squid/squid_bad_port.ini
tests/configs/squid/squid_blank_location.ini
tests/configs/squid/squid_unavailable.ini
tests/configs/squid/valid_settings.ini
tests/test_squid.py

Nothing uses them and they don't end up in the environment file.
(SOFTWARE-3152)

Drop unused squid attributes

---

config/20-bosco.ini
osg_configure/configure_modules/bosco.py

This adds an option to disable running bosco_cluster, or only run it if it hasn't already been run (if there isn't already an entry for that endpoint+batch system in bosco's clusterlist).

Allow skipping bosco_cluster (SOFTWARE-3730)
